/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author New Acer
 */
public class gitfront extends javax.swing.JFrame {

    /**
     * Creates new form gitfront
     */
    public gitfront() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel9.setFont(new java.awt.Font("Rockwell Condensed", 0, 100)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Welcome To Travello");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(310, 220, 730, 140);

        jButton1.setBackground(new java.awt.Color(51, 255, 255));
        jButton1.setFont(new java.awt.Font("Freestyle Script", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("GET IN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(620, 440, 100, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\New Acer\\Desktop\\rohit\\beachgi.gif")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-20, 0, 780, 260);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\New Acer\\Desktop\\rohit\\chile.gif")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 250, 720, 230);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\New Acer\\Desktop\\rohit\\tuscany.gif")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(640, 250, 750, 230);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\New Acer\\Desktop\\rohit\\indo.gif")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-30, 480, 690, 220);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\New Acer\\Desktop\\rohit\\ice.gif")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(630, 480, 740, 220);

        jLabel7.setFont(new java.awt.Font("Rockwell Condensed", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Travello");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 20, 120, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\New Acer\\Desktop\\rohit\\gif2.gif")); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(710, 0, 650, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new gitlogin().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gitfront.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gitfront.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gitfront.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gitfront.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gitfront().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
