/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author New Acer
 */
public class gitlogin extends javax.swing.JFrame {

    /**
     * Creates new form gitlogin
     */
    public gitlogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        az = new javax.swing.JTextField();
        ap = new javax.swing.JPasswordField();
        si = new javax.swing.JButton();
        su = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Rockwell Condensed", 0, 48)); // NOI18N
        jLabel1.setText("  Login");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(570, 170, 130, 90);

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel2.setText("USER ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(500, 320, 100, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel3.setText("PASSWORD");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(500, 380, 100, 26);
        getContentPane().add(az);
        az.setBounds(670, 320, 150, 30);

        ap.setText("jPasswordField1");
        getContentPane().add(ap);
        ap.setBounds(670, 380, 150, 30);

        si.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        si.setIcon(new javax.swing.ImageIcon("C:\\Users\\New Acer\\Desktop\\rohit\\hh.jpg")); // NOI18N
        si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siActionPerformed(evt);
            }
        });
        getContentPane().add(si);
        si.setBounds(550, 500, 180, 30);

        su.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        su.setIcon(new javax.swing.ImageIcon("C:\\Users\\New Acer\\Desktop\\rohit\\LL.jpg")); // NOI18N
        su.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suActionPerformed(evt);
            }
        });
        getContentPane().add(su);
        su.setBounds(550, 550, 180, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\New Acer\\Desktop\\rohit\\plain-white-background.jpg")); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(460, 150, 370, 480);

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(460, 140, 380, 480);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\New Acer\\Desktop\\rohit\\background-blur-clean-531880.jpg")); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 1390, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siActionPerformed

    
            String e=az.getText();
            String f= new String(ap.getPassword());
            
    }//GEN-LAST:event_siActionPerformed

    private void suActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suActionPerformed
        new gitregister().setVisible(true);
        this.dispose();
        // TODO add your ha// TODO add your handling code here:
    }//GEN-LAST:event_suActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gitlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gitlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gitlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gitlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gitlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ap;
    private javax.swing.JTextField az;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton si;
    private javax.swing.JButton su;
    // End of variables declaration//GEN-END:variables
}
