/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author New Acer
 */
public class gitregister extends javax.swing.JFrame {

    /**
     * Creates new form gitregister
     */
    public gitregister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        registerbtn = new javax.swing.JButton();
        qw = new javax.swing.JTextField();
        qr = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        qa = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        qe = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel5.setText("EMAIL");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 380, 176, 60);

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel6.setText("PASSWORD");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(100, 430, 176, 60);

        registerbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        registerbtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\New Acer\\Desktop\\rohit\\CREATE.jpg")); // NOI18N
        registerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbtnActionPerformed(evt);
            }
        });
        getContentPane().add(registerbtn);
        registerbtn.setBounds(150, 550, 290, 40);

        qw.setText("ABC");
        getContentPane().add(qw);
        qw.setBounds(310, 280, 160, 30);

        qr.setText("ASD@gmail.com");
        getContentPane().add(qr);
        qr.setBounds(310, 390, 160, 30);

        jLabel2.setFont(new java.awt.Font("Rockwell", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(6, 0, 6));
        jLabel2.setText("SIGN-UP");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 170, 162, 80);

        qa.setText("12345");
        getContentPane().add(qa);
        qa.setBounds(310, 440, 160, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel3.setText("FIRST NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 260, 176, 70);

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel4.setText("LAST NAME");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 320, 100, 70);

        qe.setText("XYZ");
        qe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qeActionPerformed(evt);
            }
        });
        getContentPane().add(qe);
        qe.setBounds(310, 330, 160, 30);

        jLabel7.setFont(new java.awt.Font("Rockwell Condensed", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Travello");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 30, 120, 40);

        jButton2.setBackground(new java.awt.Color(76, 168, 240));
        jButton2.setFont(new java.awt.Font("Rockwell Condensed", 0, 18)); // NOI18N
        jButton2.setText("HOTELS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(530, 40, 90, 20);

        jButton3.setFont(new java.awt.Font("Rockwell Condensed", 0, 18)); // NOI18N
        jButton3.setText("FLIGHTS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(650, 40, 100, 20);

        jLabel9.setFont(new java.awt.Font("Rockwell Condensed", 0, 21)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Call Us On +91-6264-748172");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(1060, 40, 220, 30);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(80, 160, 420, 520);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\New Acer\\Desktop\\rohit\\hvhjvj (1).jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1360, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbtnActionPerformed
        

     
            String FN=qw.getText();
            String LN=qe.getText();
            String Email=qr.getText();
          

    }//GEN-LAST:event_registerbtnActionPerformed

    private void qeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ;        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gitregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gitregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gitregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gitregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gitregister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField qa;
    private javax.swing.JTextField qe;
    private javax.swing.JTextField qr;
    private javax.swing.JTextField qw;
    private javax.swing.JButton registerbtn;
    // End of variables declaration//GEN-END:variables
}
